language: node_js
node_js:
- '4.2'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
services:
before_install:
- openssl aes-256-cbc -K $encrypted_a2f47a5da016_key -iv $encrypted_a2f47a5da016_iv
  -in .travis/travis_rsa.pem.enc -out .travis/travis_rsa.pem -d
- npm update -g npm
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
after_script:
notifications:
  email: true
after_failure: cat /home/travis/build/lathonez/clicker/npm-debug.log
branches:
  only:
  - master
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis_rsa.pem
- ssh-add .travis/travis_rsa.pem
- rm .gitignore
- git add www/build/test/app
- git -c user.name='travis' -c user.email='travis@travis-ci.org' commit -m "updating compiled tests [ci skip]"
- git push origin master
- cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js && rm -rf coverage
- npm install -g cordova ionic
- ionic platform add android
- ionic build android
- ionic upload --email $IONIC_EMAIL --password $IONIC_PASSWORD
