#
# Configuration
#

language: android

android:
  components:
    - android-22
    - build-tools-23.0.1
    - platform-tools

env:
  - CXX=g++-4.8

notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: required

branches:
  only:
  - master

#
# Build Lifecycle:
#

before_install:
  - rm -rf /home/travis/.nvm
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm update -g npm
  # The following three lines came from angular-seed, unsure
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: npm install

before_script:

script: npm test

after_failure: cat /home/travis/build/lathonez/clicker/npm-debug.log

after_success:
  # push compiled TS to test folder in git for reference in coveralls
  - .travis/push_built_tests.sh
  # Send coverage info off to cloud ppl
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - cat coverage/lcov.info | ./node_modules/.bin/codecov

before_deploy:
  # build for android
  - sudo npm install -g cordova ionic
  - ionic platform add android
  - ionic build android

deploy:
  # now deploying to davonez as ionic view is a pile of wank
  # - ionic upload --email $IONIC_EMAIL --password $IONIC_PASSWORD
  - ssh-keyscan 176.58.107.25  >> ~/.ssh/known_hosts
  - scp -i .travis/travis_rsa.pem platforms/android/build/outputs/apk/android-debug.apk shazleto@176.58.107.25:~/clicker
