#
# Configuration 
#

language: android

android:
  components:
    - android-23
    - build-tools-23.0.2
    - platform-tools

env:
  - CXX=g++-4.8

notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: required

branches:
  only:
  - master

#
# Build Lifecycle:
#

before_install:
  - rm -rf /home/travis/.nvm                                         #
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -   # upgrade node manually as we're building on
  - sudo apt-get install -y nodejs                                   # android language and can't pick it in yml
  - sudo npm update -g npm
  - sudo npm install -g cordova ionic
  # Everything below here is installing latest chrome
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install -y google-chrome-stable

install:
  - npm install
  - ionic state restore # install cordova stuff from package.json
  - npm run webdriver-update

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test                             # unit tests
  - npm run build                        # ionic build
  - sleep 10                             # allow time for ionic to build
  # Serve with python as ionic serve needs interaction
  - cd www && python -m SimpleHTTPServer 8100 >> python_serve.log 2>&1 &
  - npm run e2e                          # run e2e tests against ionic

after_failure:
  - cat /home/travis/build/lathonez/clicker/python_serve.log
  - cat /home/travis/build/lathonez/clicker/ionic_serve.log

after_success:
  # push compiled TS to test folder in git for reference in coveralls
  - .travis/push_built_tests.sh
  # Send coverage info off to cloud ppl
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - cat coverage/lcov.info | ./node_modules/.bin/codecov

before_deploy:
  # build for android
  - ionic build android

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
