#
# Configuration
#

language: android

android:
  components:
    - android-23
    - build-tools-23.0.2
    - platform-tools

env:
  - CXX=g++-4.8

notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: required

branches:
  only:
    - master
    - lightweightify

#
# Build Lifecycle:
#

before_install:
  - rm -rf /home/travis/.nvm                                         #
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -   # upgrade node manually as we're building on
  - sudo apt-get install -y nodejs                                   # android language and can't pick it in yml
  - sudo npm update -g npm
  - sudo npm install -g cordova ionic
  # Everything below here is installing the last version of chrome that supports ubuntu 12.*
  - wget http://mirror.pcbeta.com/google/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_49.0.2623.87-1_amd64.deb
  - sudo dpkg -i google-chrome-stable_49.0.2623.87-1_amd64.deb
  - sudo apt-get -f install

install:
  - npm install
  - ionic state restore # install cordova stuff from package.json
  - npm run webdriver-update

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test                             # unit tests
  - npm run build                        # ionic build
  # Serve with python as ionic serve needs interaction
  - cd www && python -m SimpleHTTPServer 8100 >> python_serve.log 2>&1 &
  - npm run e2e                          # run e2e tests against ionic

after_failure:
  - cat /home/travis/build/lathonez/clicker/python_serve.log
  - cat /home/travis/build/lathonez/clicker/ionic_serve.log

after_success:
  # Send coverage info off to cloud ppl
  - cat coverage/lcov.info | ./node_modules/.bin/codecov

before_deploy:
  # build for android
  - ionic build android

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
