#
# Configuration
#

language: android

android:
  components:
    - android-23
    - build-tools-23.0.2
    - platform-tools

env:
  - CXX=g++-4.8

notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: required

branches:
  only:
  - master

#
# Build Lifecycle:
#

before_install:
  - rm -rf /home/travis/.nvm                                         #
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -   # upgrade node manually as we're building on
  - sudo apt-get install -y nodejs                                   # android language and can't pick it in yml
  - sudo npm update -g npm
  - sudo npm install -g cordova ionic
  - sudo apt-get install -y chromium-browser                         # need new version for E2E

install:
  - npm install
  - ionic state restore # install cordova stuff from package.json
  - npm run webdriver-update

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test                             # unit tests
  - ionic serve -b --address localhost >> ionic_serve.log 2>&1 &
  - sleep 10                             # allow time for ionic serve to start up
  - npm run e2e                          # run e2e tests against ionic

after_failure:
  - cat /home/travis/build/lathonez/clicker/npm-debug.log
  - cat /home/travis/build/lathonez/clicker/ionic_serve.log

after_success:
  # push compiled TS to test folder in git for reference in coveralls
  - .travis/push_built_tests.sh
  # Send coverage info off to cloud ppl
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - cat coverage/lcov.info | ./node_modules/.bin/codecov

before_deploy:
  # build for android
  - ionic build android

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
