# Test against this version of Node.js
environment:
  nodejs_version: "6.5"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g cordova ionic angular-cli
  - ionic state clear
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - ng test --watch=false

build: off

deploy:
- provider: Local
  AppVeyor-Protractor-test-app.deploy_website: true
  AppVeyor-Protractor-test-app.site_name: Test
  AppVeyor-Protractor-test-app.hostname: localhost
  AppVeyor-Protractor-test-app.port: 47602
  AppVeyor-Protractor-test-app.protocol: http
  AppVeyor-Protractor-test-app.remove_files: true

before_deploy:
  - npm run ionic:build

after_deploy:
  - npm run e2e