#
# Clicker CircleCI 2.0 configuration file
#
version: 2.0
jobs:
  build:
    docker:
      - image: lathonez/ionic-selenium:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install deps
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # dump env for debug
      - run:
          name: debug environment
          command: ionic info

      - run:
         name: lint
         command: npm run lint

      - run:
          name: unit test
          environment:
            DISPLAY: :99
            CHROME_BIN: /usr/bin/google-chrome
          command: xvfb-run npm run test-ci

      - run:
          name: e2e test
          environment:
            DISPLAY: :99
            CHROME_BIN: /usr/bin/google-chrome
          command: xvfb-run npm run e2e