#
# Clicker CircleCI 2.0 configuration file
#
version: 2.0
jobs:
  build:
    docker:
      - image: lathonez/ionic-selenium:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install deps
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # dump env for debug
      - run:
          name: debug environment
          command: ionic info

      - run:
         name: lint
         command: npm run lint

      - run:
          name: unit test
          environment:
            DISPLAY: :99
            CHROME_BIN: /usr/bin/google-chrome
            JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/junit/
            JUNIT_REPORT_NAME: unit-test-results.xml
          command: xvfb-run npm run test-ci

      - run:
          name: upload coverage
          environment:
            CODECOV_TOKEN: 82961927-13cb-4813-928f-55e6d09daa93
          command: cat ./coverage/lcov.info | ./node_modules/.bin/codecov

      - run:
          name: e2e test
          environment:
            DISPLAY: :99
            CHROME_BIN: /usr/bin/google-chrome
            JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/junit/
          command: xvfb-run npm run e2e

      - run:
          name: Prepare
          command: ionic cordova prepare

      - run:
          name: Build
          command: ionic cordova build browser